import { Article } from './types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: 1,
    source_type: 'news',
    source_name: 'BBC News',
    topic: 'Artificial Intelligence',
    title: 'AI Regulation: Global Leaders Meet to Discuss Framework',
    body: 'World leaders convened today to establish guidelines for artificial intelligence development, emphasizing the need for balanced oversight that promotes innovation while protecting citizens.',
    url: 'https://example.com/bbc-ai',
    published_at: '2024-03-15T10:30:00Z',
    sentiment_score: 0.3,
    bias_score: -1.5,
    emotion: 'neutral',
    bias_label: 'center-left',
    loaded_words: ['balanced', 'protecting'],
    main_claim: 'International cooperation is essential for AI governance',
    framing: 'opportunity',
    missing_voices: 'Tech industry representatives from developing nations'
  },
  {
    id: 2,
    source_type: 'reddit',
    source_name: 'r/technology',
    topic: 'Artificial Intelligence',
    title: 'OpenAI just killed another competitor - this monopoly is getting out of control',
    body: 'Yet another AI startup acquired. The concentration of power in Silicon Valley tech giants threatens innovation and consumer choice. We need antitrust action NOW.',
    url: 'https://reddit.com/r/technology/example',
    published_at: '2024-03-15T08:15:00Z',
    sentiment_score: -0.7,
    bias_score: -4.5,
    emotion: 'outrage',
    bias_label: 'left',
    loaded_words: ['monopoly', 'killed', 'threatens'],
    main_claim: 'Big Tech consolidation harms the AI ecosystem',
    framing: 'threat',
    missing_voices: 'Startup founders, acquisition targets'
  },
  {
    id: 3,
    source_type: 'news',
    source_name: 'Fox News',
    topic: 'Artificial Intelligence',
    title: 'Biden Admin AI Rules Could Cripple American Innovation',
    body: 'The proposed AI regulations threaten to hand our technological advantage to China. Business leaders warn of job losses and economic decline if overreaching government controls proceed.',
    url: 'https://example.com/fox-ai',
    published_at: '2024-03-15T11:00:00Z',
    sentiment_score: -0.5,
    bias_score: 6.5,
    emotion: 'negative',
    bias_label: 'right',
    loaded_words: ['cripple', 'overreaching', 'threaten'],
    main_claim: 'Government regulation will harm US competitiveness',
    framing: 'threat',
    missing_voices: 'Consumer advocacy groups, AI safety researchers'
  },
  {
    id: 4,
    source_type: 'blog',
    source_name: 'TechCrunch',
    topic: 'Artificial Intelligence',
    title: 'The State of AI in 2024: A Balanced Assessment',
    body: 'Our annual review examines the progress and challenges in artificial intelligence. While capabilities have advanced significantly, concerns about bias and transparency remain valid.',
    url: 'https://techcrunch.com/ai-2024',
    published_at: '2024-03-14T16:00:00Z',
    sentiment_score: 0.2,
    bias_score: 0.5,
    emotion: 'neutral',
    bias_label: 'center',
    loaded_words: [],
    main_claim: 'AI progress comes with legitimate concerns that need addressing',
    framing: 'neutral',
    missing_voices: 'End users affected by AI systems'
  },
  {
    id: 5,
    source_type: 'reddit',
    source_name: 'r/Conservative',
    topic: 'Artificial Intelligence',
    title: 'Woke AI Censorship: ChatGPT refuses to write anything conservative',
    body: 'Tried to get ChatGPT to write a conservative viewpoint and it refused. Meanwhile it happily writes liberal talking points. The bias in AI is undeniable and dangerous.',
    url: 'https://reddit.com/r/conservative/example',
    published_at: '2024-03-15T07:30:00Z',
    sentiment_score: -0.8,
    bias_score: 8.0,
    emotion: 'outrage',
    bias_label: 'far-right',
    loaded_words: ['woke', 'censorship', 'dangerous'],
    main_claim: 'AI systems are politically biased against conservatives',
    framing: 'conflict',
    missing_voices: 'AI developers, content moderation experts'
  },
  {
    id: 6,
    source_type: 'news',
    source_name: 'Reuters',
    topic: 'Artificial Intelligence',
    title: 'Tech Companies Report Mixed Q4 Results Amid AI Investment Surge',
    body: 'Major technology firms posted quarterly earnings that reflected substantial AI infrastructure investments. Analysts note varying returns on these expenditures across the sector.',
    url: 'https://reuters.com/tech-q4',
    published_at: '2024-03-15T09:00:00Z',
    sentiment_score: 0.1,
    bias_score: 0.0,
    emotion: 'neutral',
    bias_label: 'center',
    loaded_words: [],
    main_claim: 'AI investments are showing mixed financial returns',
    framing: 'neutral',
    missing_voices: 'Retail investors, pension fund managers'
  },
  {
    id: 7,
    source_type: 'blog',
    source_name: 'The Verge',
    topic: 'Artificial Intelligence',
    title: 'AI Art Generators Are Getting Scary Good - And Artists Are Furious',
    body: 'The latest generation of AI image tools can replicate any style with disturbing accuracy. Creative professionals face an existential threat as their work is scraped without consent.',
    url: 'https://theverge.com/ai-art',
    published_at: '2024-03-14T14:30:00Z',
    sentiment_score: -0.4,
    bias_score: -2.0,
    emotion: 'negative',
    bias_label: 'center-left',
    loaded_words: ['scary', 'furious', 'existential threat'],
    main_claim: 'AI image generation threatens human artists livelihoods',
    framing: 'threat',
    missing_voices: 'AI tool developers, consumers benefiting from AI art'
  },
  {
    id: 8,
    source_type: 'reddit',
    source_name: 'r/MachineLearning',
    topic: 'Artificial Intelligence',
    title: '[D] New paper shows transformers have fundamental scaling limitations',
    body: 'Interesting research suggesting current architectures may hit walls. Discussion of alternative approaches and what this means for AGI timelines.',
    url: 'https://reddit.com/r/machinelearning/example',
    published_at: '2024-03-15T12:00:00Z',
    sentiment_score: 0.0,
    bias_score: 0.2,
    emotion: 'neutral',
    bias_label: 'center',
    loaded_words: [],
    main_claim: 'Current AI scaling approaches have technical limitations',
    framing: 'neutral',
    missing_voices: 'Industry practitioners implementing these systems'
  },
  {
    id: 9,
    source_type: 'news',
    source_name: 'MSNBC',
    topic: 'Artificial Intelligence',
    title: 'AI Surveillance: How Corporations Track Your Every Move',
    body: 'Investigation reveals extent of AI-powered surveillance in everyday life. Privacy advocates call for immediate legislative action to protect civil liberties.',
    url: 'https://msnbc.com/ai-surveillance',
    published_at: '2024-03-14T20:00:00Z',
    sentiment_score: -0.6,
    bias_score: -5.0,
    emotion: 'negative',
    bias_label: 'left',
    loaded_words: ['surveillance', 'track', 'every move'],
    main_claim: 'Corporate AI surveillance threatens privacy rights',
    framing: 'threat',
    missing_voices: 'Tech companies, security professionals'
  },
  {
    id: 10,
    source_type: 'blog',
    source_name: 'Wired',
    topic: 'Artificial Intelligence',
    title: 'Inside the Race to Build Safe Superintelligence',
    body: 'We spent a week with AI safety researchers working to ensure advanced AI systems remain aligned with human values. Their work may determine our future.',
    url: 'https://wired.com/ai-safety',
    published_at: '2024-03-15T06:00:00Z',
    sentiment_score: 0.3,
    bias_score: -1.0,
    emotion: 'positive',
    bias_label: 'center-left',
    loaded_words: ['race', 'determine our future'],
    main_claim: 'AI safety research is critical for humanitys future',
    framing: 'opportunity',
    missing_voices: 'AI capabilities researchers, deployment teams'
  },
  {
    id: 11,
    source_type: 'news',
    source_name: 'Wall Street Journal',
    topic: 'Artificial Intelligence',
    title: 'Enterprise AI Adoption Accelerates as ROI Becomes Clear',
    body: 'Fortune 500 companies report significant productivity gains from AI deployment. CFOs increasingly view AI investment as essential for competitive positioning.',
    url: 'https://wsj.com/enterprise-ai',
    published_at: '2024-03-15T05:30:00Z',
    sentiment_score: 0.6,
    bias_score: 3.0,
    emotion: 'positive',
    bias_label: 'center-right',
    loaded_words: ['accelerates', 'essential'],
    main_claim: 'AI provides clear business value for enterprises',
    framing: 'opportunity',
    missing_voices: 'Workers displaced by AI, small businesses'
  },
  {
    id: 12,
    source_type: 'reddit',
    source_name: 'r/worldnews',
    topic: 'Artificial Intelligence',
    title: 'EU passes landmark AI Act - strictest regulations in the world',
    body: 'The European Union has finalized comprehensive AI legislation. Critics argue it goes too far, supporters say it sets important precedents for protecting citizens.',
    url: 'https://reddit.com/r/worldnews/ai-act',
    published_at: '2024-03-15T13:00:00Z',
    sentiment_score: 0.2,
    bias_score: -0.5,
    emotion: 'neutral',
    bias_label: 'center',
    loaded_words: ['landmark', 'strictest'],
    main_claim: 'EU leads global AI regulation efforts',
    framing: 'neutral',
    missing_voices: 'EU tech startups affected by compliance costs'
  }
];

export const MOCK_ECHO_ALERT = `The dominant narrative across sources shows a clear polarization in AI coverage. Left-leaning outlets emphasize corporate accountability and worker protection, while right-leaning sources focus on innovation concerns and government overreach. Notably absent from most coverage are the perspectives of AI researchers in academia and those from developing nations who may be most affected by these policies. For a more balanced view, consider seeking out academic publications and international development-focused news sources.`;

export const SUGGESTED_TOPICS = [
  'Artificial Intelligence',
  'Climate Change',
  'Immigration Policy',
  'Economic Policy',
  'Healthcare Reform',
  'Election 2024',
  'Cryptocurrency',
  'Remote Work'
];
